p8105_hw2
================
yl6378
2026-10-07

# Problem 1

``` r
subway_df = read_csv(
  "data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv"
) |>
  select(
    Line,
    `Station Name`,
    `Station Latitude`,
    `Station Longitude`,
    Route1:Route11,
    `Entrance Type`,
    Entry,
    Vending,
    ADA
  ) |>
  mutate(
    Entry = if_else(Entry == "YES", TRUE, FALSE)
  )
```

    ## Rows: 1868 Columns: 32
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (22): Division, Line, Station Name, Route1, Route2, Route3, Route4, Rout...
    ## dbl  (8): Station Latitude, Station Longitude, Route8, Route9, Route10, Rout...
    ## lgl  (2): ADA, Free Crossover
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

After cleaning, the subway dataset contains 1,868 observations and 19
variables. The retained variables include subway line and station
information, station latitude and longitude, routes served, entrance
type, entry status, vending availability, and ADA accessibility. I also
converted the `Entry` variable from `"YES"` / `"NO"` to a logical
variable. At this stage, the data are not fully tidy because route
information is spread across multiple columns (`Route1` through
`Route11`) rather than stored in a single route variable.

``` r
subway_df |>
  distinct(Line, `Station Name`) |>
  nrow()
```

    ## [1] 465

There are 465 distinct subway stations.

``` r
subway_df |>
  filter(ADA == TRUE) |>
  distinct(Line, `Station Name`) |>
  nrow()
```

    ## [1] 84

There are 84 ADA-compliant subway stations.

``` r
subway_df |>
  filter(Vending == "NO") |>
  summarize(
    total = n(),
    entry_yes = sum(Entry),
    prop_entry = entry_yes / total
  )
```

    ## # A tibble: 1 × 3
    ##   total entry_yes prop_entry
    ##   <int>     <int>      <dbl>
    ## 1   183        69      0.377

Among station entrances and exits without vending machines, 69 out of
183 allow entrance. This corresponds to a proportion of approximately
37.7%.

``` r
subway_long = subway_df |>
  mutate(
    across(Route1:Route11, as.character)
  ) |>
  pivot_longer(
    Route1:Route11,
    names_to = "route_number",
    values_to = "route_name",
    values_drop_na = TRUE
  )
```

The route variables are reshaped from wide to long format. The original
`Route1` through `Route11` columns are converted into two variables:
`route_number`, which indicates the original route column, and
`route_name`, which contains the subway route served.

``` r
subway_long |>
  filter(route_name == "A") |>
  distinct(Line, `Station Name`) |>
  nrow()
```

    ## [1] 60

There are 60 distinct subway stations that serve the A train

``` r
subway_long |>
  filter(route_name == "A", ADA == TRUE) |>
  distinct(Line, `Station Name`) |>
  nrow()
```

    ## [1] 17

Among the stations that serve the A train, 17 are ADA compliant

# Problem 2

# Problem 3
